DROP DATABASE IF EXISTS integracao;
CREATE DATABASE integracao;
USE integracao;

CREATE TABLE IF NOT EXISTS Cliente (
    idCliente INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(45),
    CPF VARCHAR(11) UNIQUE,
    Email VARCHAR(45) UNIQUE,
    Telefone VARCHAR(15)
);

CREATE TABLE IF NOT EXISTS Mesa (
    idMesa INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Numero INT NOT NULL,
    Capacidade INT NOT NULL
);
